name: Lint PR Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: wagoid/commitlint-github-action@v5

